jina=input("Enter your name:")
nambari1=float(input("Enter first number"))
nambari2=float(input("Enter second number"))
# print(f"The sum of {nambari1} and {nambari2} is {nambari1+nambari2}")
# print(f"The product of {nambari1} and {nambari2} is {nambari1*nambari2}")
# print(f"The difference of {nambari1} and {nambari2} is {nambari1-nambari2}")
# print(f"The quotient of {nambari1} and {nambari2} is {nambari1/nambari2}")
print(f"Welcome {jina} at eMobilis")
print(f"The sum of {nambari1} and {nambari2} is {nambari1+nambari2}")